import { createRoot } from 'react-dom/client'
import React, { useRef, useState, useEffect, useFrame, Suspense } from 'react'
import { Canvas } from '@react-three/fiber'
import { Text, useGLTF } from '@react-three/drei';
import './styles.css'
import { MathUtils } from 'three/src/Three.Core.js';
import { rotate } from 'three/tsl';

function Model({ hinge, ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/leon.glb')
  const [hovered, setHovered] = useState(false)
  useEffect(() => void (document.body.style.cursor = hovered ? 'pointer' : 'auto'), [hovered])
  // Make it float in the air when it's opened
  useFrame((state) => {
    const t = state.clock.getElapsedTime()
    group.current.rotation.x = MathUtils.lerp(group.current.rotation.x, Math.cos(t / 10) / 10 + 0.25, 0.1)
    group.current.rotation.y = MathUtils.lerp(group.current.rotation.y, Math.sin(t / 10) / 4, 0.1)
    group.current.rotation.z = MathUtils.lerp(group.current.rotation.z, Math.sin(t / 10) / 10, 0.1)
    group.current.position.y = MathUtils.lerp(group.current.position.y, (-2 + Math.sin(t)) / 3, 0.1)
  })
  // The view was auto-generated by: https://github.com/pmndrs/gltfjsx
  // Events and spring animations were added afterwards
  return (
    <group ref={group} {...props} onPointerOver={(e) => (e.stopPropagation(), setHovered(true))} onPointerOut={() => setHovered(false)} dispose={null}>
      <group rotation-x={hinge} position={[0, -0.04, 0.41]}>
        <group position={[0, 2.96, -0.13]} rotation={[Math.PI / 2, 0, 0]}>
          <mesh material={materials.aluminium} geometry={nodes['Cube008'].geometry} />
          <mesh material={materials['matte.001']} geometry={nodes['Cube008_1'].geometry} />
          <mesh material={materials['screen.001']} geometry={nodes['Cube008_2'].geometry} />
        </group>
      </group>
      <mesh material={materials.keys} geometry={nodes.keyboard.geometry} position={[1.79, 0, 3.45]} />
      <group position={[0, -0.1, 3.39]}>
        <mesh material={materials.aluminium} geometry={nodes['Cube002'].geometry} />
        <mesh material={materials.trackpad} geometry={nodes['Cube002_1'].geometry} />
      </group>
      <mesh material={materials.touchbar} geometry={nodes.touchbar.geometry} position={[0, -0.03, 1.2]} />
    </group>
  )
}

function NavScene(props) {
  // This reference will give us direct access to the mesh
  const meshRef1 = useRef()
  const meshRef2 = useRef()
  const meshRef3 = useRef()
  const mainView = useRef()
  // Set up state for the hovered and active state
  const [hovered, setHover] = useState(false)
  const [activePage, setActivePage] = useState(null)
  const [textRotations, setTextRotations] = useState({Code: 0, Design: 0, Skills: 0})

  // Subscribe this component to the render-loop, rotate the mesh every frame
  // useFrame((state, delta) => {
  //   navMeshRefs.forEach((ref) => {
  //     ref.current.rotation.x += activePage ? 0 : delta
  //   })
  // })

  const pages = [
    { name: 'Code', path: '/software' },
    { name: 'Design', path: '/design' },
    { name: 'Skills', path: '/skills' },
  ]

  const pagesO = {
    Code:
      { 
        name: 'Code',
        path: '/software',
        links: [{id:'Goal Coach',link: 'https://goalcoach-kp.streamlit.app/'}, {id:'Goal Better', link:''}] },
    Design: { name: 'Design', path: '/design' },
    Skills: { name: 'Skills', path: '/skills' }
  }

  const navMeshRefs = [meshRef1, meshRef2, meshRef3];

  const handlePageClick = (pageName) => {
    if(activePage === pageName) {
      setActivePage(null);
      return;
    }
    setActivePage(pageName);
  }

  const rotateText = (angle, targetName) => {
    const newRotations = { ...textRotations };
    newRotations[targetName] = angle
    setTextRotations(targetName ? newRotations : {Code: 0, Design: 0, Skills: 0});
  }

  const goToLink = (link) => {
    return () => {
      if(link) {
        window.open(link, '_blank');
      }
    }
  }

  return (
    <>
      <mesh
        {...props}
        style={{ cursor: hovered ? 'pointer' : 'auto', width: '100%', height: '100%' }}
        scale={activePage ? 6 : 1}>
        <boxGeometry args={[1, 1, 1]} />
        {activePage && pagesO[activePage].links && pagesO[activePage].links.length > 0 && pagesO[activePage].links.map((linkObj, index) => {
            return (
                <mesh onClick={goToLink(linkObj.link)}>
                  <Text
                    position={[-(index/pagesO[activePage].links.length), 0, 0.51]}
                    fontSize={0.02}
                    color={'white'}
                  >
                  {linkObj.id}
                  </Text>
                </mesh>
              )
          })}
        <meshStandardMaterial color={hovered ? 'red' : 'black'} />
      </mesh>
      {/* <mesh>
        <Suspense fallback={null}>
          <group rotation={[0, Math.PI, 0]}>
                <Model hinge={[1.575, -0.425]} />
          </group>
        </Suspense>
      </mesh> */}
      <mesh style={{ position: 'absolute', bottom: 3, width: '100%', textAlign: 'center'}}>
        <group position={[-pages.length / 2, -4, 0]}>
          {Object.entries(pagesO).map(([key, p], i) => {
            return (
              <Text
                key={p.name}
                ref={navMeshRefs[i]}
                position={[activePage === p.name ? 1.5 : i === 3 ? i : i * 1.7, 0, 0]} // TODO: Adjust the multiplier for spacing of items
                fontSize={activePage === p.name ? .6 : 0.3} // Enlarge active text
                color={'white'}
                // color={activePage === p.name ? 'darkred' : 'white'}
                onClick={() => handlePageClick(p.name)}
                onPointerOver={() => rotateText(.5, p.name)}
                onPointerOut={() => rotateText(0, null)}
                rotation={[textRotations[p.name], (Math.PI / 180) * (i * 10), 0]} // Rotate text horizontally
              >
                {activePage === p.name ? p.name : !activePage ? p.name : ''}
              </Text>
            )
          })}
        </group>
      </mesh>
    </>

  )}
createRoot(document.getElementById('root')).render(
  <Canvas>
    <ambientLight intensity={Math.PI / 2} />
    <spotLight position={[10, 10, 10]} angle={0.15} penumbra={1} decay={0} intensity={Math.PI} />
    <pointLight position={[-10, -10, -10]} decay={0} intensity={Math.PI} />
    <NavScene position={[0, 0, 0]} />
  </Canvas>
)

export default NavScene